- name: "Create multiple users from a file"
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - users.yml
  tasks:
    - name: "Adding Users"
      user:
        name: "{{ item.name }}"
        create_home: yes
        password: "{{ lookup('password', 'credentials/' + item.name + '/password.txt length=20 chars=ascii_letters')}}"
        state: present
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/{{ item.name }}
        ssh_key_passphrase: "{{ lookup('password', 'credentials/' + item.name + '/passphrase.txt length=20 chars=ascii_letters')}}"
      register: useradd_complete
      with_items: "{{ users }}"
    - name: execute install script
      command: python3  shell.py3
      register: current_config
    - debug: msg="{{ current_config.stdout_lines }}"
    - name: write config to local file
      local_action:
          module: copy
          content: "{{ current_config.stdout_lines|join('\n')}}"
          dest: test.txt